services:
  db:
    image: postgres:16-alpine
    container_name: local_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_LOCAL_USER}
      - POSTGRES_PASSWORD=${POSTGRES_LOCAL_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - app-networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_LOCAL_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  local_pgdata: {}
  pgadmin-data: {} 

networks:
  app-networks:


  