
default: &default
  adapter: postgresql
  encoding: unicode

  # username: <%= ENV['POSTGRES_LOCAL_USER'] %>
  # password: <%= ENV['POSTGRES_LOCAL_PASSWORD'] %>
  # host: <%= ENV['POSTGRES_HOST'] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_LOCAL_USER'] %>
  password: <%= ENV['POSTGRES_LOCAL_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>


production:
  <<: *default
  database: odds_janitor_production
  username: odds_janitor
  password: <%= ENV["ODDS_JANITOR_DATABASE_PASSWORD"] %>
